modLoader = "javafml"
loaderVersion = "[36,)"
license = "AGPLv3"

[[mods]]
modId = "i18nupdatemod"
version = "${version}"
displayName = "I18nUpdateMod NLTS"
authors = "LocalizedMC, TexTrue"
description = '''
I18nUpdateMod NLTS
'''
#logoFile = ""

[[dependencies.i18nupdatemod]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.i18nupdatemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.i18nupdatemod]]
modId = "architectury"
mandatory = true
versionRange = "[9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.i18nupdatemod]]
modId = "cloth_config"
mandatory = true
versionRange = "[11,)"
ordering = "AFTER"
side = "BOTH"